users_credentials = [
    'john.doe@gmail.com', 'P@ssw0rd',
    'alice.smith@yahoo.com', 'Secure123',
    'bob.jones@hotmail.com', 'StrongPwd!',
    'emma.white@gmail.com', 'Secret456',
    'chris.miller@yahoo.com', 'Pa$$w0rd!',
    'lisa.johnson@hotmail.com', 'Secure789',
    'mike.wilson@gmail.com', 'P@ssword123',
    'sara.martin@yahoo.com', 'StrongPwd456',
    'ryan.clark@hotmail.com', 'Secret789',
    'emily.brown@gmail.com', 'Pa$$word!',
    'david.hall@yahoo.com', 'SecureABC',
    'olivia.smith@hotmail.com', 'StrongPwd789',
    'daniel.jones@gmail.com', 'P@ssword456',
    'mia.taylor@yahoo.com', 'Secret123',
    'james.wilson@hotmail.com', 'Pa$$w0rdABC',
    'lily.jackson@gmail.com', 'SecureXYZ',
    'noah.white@yahoo.com', 'Strong789',
    'ava.anderson@hotmail.com', 'P@sswordXYZ',
    'william.hill@gmail.com', 'SecretXYZ',
    'sophia.evans@yahoo.com', 'Pa$$w0rd789',
    'logan.brown@hotmail.com', 'Secure456',
    'grace.davis@gmail.com', 'P@ssword789',
    'oliver.martin@yahoo.com', 'StrongXYZ',
    'amelia.moore@hotmail.com', 'Pa$$w0rd456',
    'henry.carter@gmail.com', 'SecureABC'
]
